SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BottleOrder](
	[BottleOrder] [int] NOT NULL,
	[ClientID] [int] NULL,
	[Contact] [varchar](50) NULL,
	[ProjectID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[BottleOrder] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
